apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: proxy
        image: javier171188/client
        ports:
        - containerPort: 1234
        env:
        - name: SOCKET_ENDPOINT
          value: "http://proxy-service"
        - name: SOCKET_PATH
          value: "/mysocket"
        - name: USER_PATH
          value: "http://proxy-service:80/users"
        
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      