apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: javier171188/user
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: SECRET_SIGN
          value: "secretsign"
        - name: DB_URL
          value: "mongodb://userdb-service:27017"
        - name: DB_NAME
          value: "users-chat"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
      - name: userdb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: uservolume
          mountPath: /data/db
      volumes:
      - name: uservolume
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-service
spec:
  selector:
    app: userdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatsdb
  labels:
    app: chatsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatsdb
  template:
    metadata:
      labels:
        app: chatsdb
    spec:
      containers:
      - name: chatsdb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: chatsvolume
          mountPath: /data/db
      volumes:
      - name: chatsvolume
---
apiVersion: v1
kind: Service
metadata:
  name: chatsdb-service
spec:
  selector:
    app: chatsdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats
  labels:
    app: chats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats
  template:
    metadata:
      labels:
        app: chats
    spec:
      containers:
      - name: chats
        image: javier171188/chats
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB_URL
          value: "mongodb://chatsdb-service:27017"
        - name: DB_NAME
          value: "chats-chat"
---
apiVersion: v1
kind: Service
metadata:
  name: chats-service
spec:
  selector:
    app: chats
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: javier171188/proxy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: javier171188/client
        ports:
        - containerPort: 1234
        env:
        - name: SOCKET_ENDPOINT
          value: "http://a938bdc87604b4c9db73f8ef00edcfb0-1033339092.us-east-2.elb.amazonaws.com:80/"
        - name: SOCKET_PATH
          value: "/mysocket"
        - name: USER_PATH
          value: "http://a938bdc87604b4c9db73f8ef00edcfb0-1033339092.us-east-2.elb.amazonaws.com:80/users"
        
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
