version: "3.8"

services:
  app:
    build: .
    environment:
      PORT: "3000"
      SECRET_SIGN: "secretsign"
      DB_URL: "mongodb://db:27017"
      DB_NAME: "users-chat"
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: mongo