apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
      - name: userdb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: uservolume
          mountPath: /data/db
      volumes:
      - name: uservolume
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-service
spec:
  selector:
    app: userdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
