apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: javier171188/user
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: SECRET_SIGN
            value: "secretsign"
          - name: DB_URL
            value: "mongodb://10.97.81.75:27017"
          - name: DB_NAME
            value: "users-chat"
